name: Variables Workflow Level
on: 
    workflow_dispatch:
jobs:
    Docker:
        runs-on: ubuntu-latest
        ######## Environment Variables at Workflow level ########
        steps:
        - name: Docker Build
          run: echo docker build -t ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest

        - name: Docker login
          run: echo docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          
        - name: Docker Publish
          run: echo docker push ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest

    Deploy:
        needs: Docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker Run
          run: echo docker run -d -p 8080:80 ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest