name: Single Step Multiple Lines
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4.1.1

        - name: List Read Print into single step
          run: |
            echo "My First Github action job"
            ls -a
            cat README.md